Do not decode os.path.realpath / path
`path` is decoded already (coming from `db`) and this caused the
following error:

    Traceback (most recent call last):
      File "/home/user/.autojump/bin/autojump", line 460, in <module>
        if not shell_utility(): sys.exit(1)
      File "/home/user/.autojump/bin/autojump", line 429, in shell_utility
        results = find_matches(db, patterns, max_matches, False)
      File "/home/user/.autojump/bin/autojump", line 374, in find_matches
        if current_dir == decode(os.path.realpath(path)) :
      File "/home/user/.autojump/bin/autojump", line 277, in decode
        return text.decode(encoding, errors)
      File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in
    position 52: ordinal not in range(128)